# nginx reverse proxy

version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - type: bind
      #   source: ./nginx.conf
      #   target: /etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www:/var/www
      