version: '3.1'

volumes:
  global-postgres-volume:
  global-pgadmin-volume:

services:
  db:
    image: 'postgres:14.4'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db 
    ports:
      - 5432:5432
    volumes:
      - global-postgres-volume:/var/lib/postgresql/data
  pg-admin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - global-pgadmin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@mail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      